version: '3.9'

services:
  shortenurl:
    build: ./
    volumes:
    - ./config:/opt/app/config:ro
    ports:
    - 8080:8080
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "30"
    privileged: true
