version: '2'

services:
  shortenurl:
    image: guessi/node-shorten-url
    volumes:
        - ./config:/opt/app/config:ro
    ports:
        - 8080:8080
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "30"
    privileged: true
